spawns nodes with IPC disabled by default
avoids permissions issues listening on IPC socket:

```
Error: listen EPERM: operation not permitted /root/.ironfish/ironfish.ipc
```

rpc connections use TCP instead of IPC in fishtank, so IPC does not need to be
enabled by default